name: Example tests

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch.

  pull_request:
    branches:
      - main # Trigger on pull requests to the 'main' branch.

  workflow_dispatch:

env:
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  QASE_TESTOPS_PROJECT: ${{ vars.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_RUN_COMPLETE: true
  QASE_DEBUG: true
  QASE_MODE: testops

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright
          playwright install --with-deps

      - name: Set Qase Run Description with Github Link
        run: |
          GITHUB_LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "QASE_TESTOPS_RUN_DESCRIPTION=[GitHub Action Run]($GITHUB_LINK)" >> $GITHUB_ENV

      - name: Run pytest-playwright tests
        run: pytest
